event.register("initialized", function()
	require("JosephMcKean.ashfallSurvivalStart.chargen")
	require("JosephMcKean.ashfallSurvivalStart.items")
	require("JosephMcKean.ashfallSurvivalStart.loneliness")
end)