[package]
name = "Ashfall Survival Start"
description = "Ashfall Survival Start is an alternate start mod where you are the only survivor of a shipwreck and now stranded on a small, abandoned island."
repository = "https://github.com/amaliegay/ashfall-survival-start"
authors = ["JosephMcKean"]
version = "1.2.6"

[dependencies]
assets = [
    "Ashfall Survival Start.esp",
    "BookArt\\jsmk\\ass",
    "Meshes\\jsmk\\ass",
    "MWSE\\mods\\JosephMcKean\\ashfallSurvivalStart",
]

[dependencies.mwse]
buildnumber = 3251

[dependencies.mods."Skills Module"]
mwse-module = "OtherSkills"
url = "https://www.nexusmods.com/morrowind/mods/46034"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.12.1"
url = "https://www.nexusmods.com/morrowind/mods/51009"

[dependencies.mods."Ashfall"]
mwse-module = "mer.ashfall"
version = "^3.10.7"
url = "https://www.nexusmods.com/morrowind/mods/49057"

[dependencies.mods."OAAB_Data"]
version = "^2.1.9"
url = "https://www.nexusmods.com/morrowind/mods/49042"